# .github/workflows/firebase-hosting-merge.yml
name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

  # 이 부분을 추가하세요 ▼
  workflow_dispatch:
    inputs:
      env:
        description: '배포할 환경 (예: live 또는 preview)'
        required: false
        default: 'live'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # … 이하 생략 …
